### Python Crash Course

https://ihis.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/learn/lecture/20622758#content

https://ihis.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/learn/lecture/13345774#content

In [8]:
import numpy as np

### Array vs List

https://ihis.udemy.com/course/pytorch-for-deep-learning-and-computer-vision/learn/lecture/13346278#content

In [22]:
sample_array = np.arange(1,4)
array_two =  sample_array ** 2
array_three = np.power( sample_array, 3) 
array_sum = array_two + array_three
print( array_sum )

[ 2 12 36]


In [16]:
print( np.negative( sample_array) )

[-1 -2 -3]


In [18]:
print( np.exp( sample_array  ) )

[ 2.71828183  7.3890561  20.08553692]


In [19]:
print( np.log( sample_array  ) )

[0.         0.69314718 1.09861229]


In [20]:
print( np.sin( sample_array  ) )

[0.84147098 0.90929743 0.14112001]


### Multi-dimensions Array

In [21]:
x = np.arange(3)
y = np.arange(3)
z = np.arange(3)
m_arr = np.array([x,y,z])
print(x)
print( m_arr.shape )
print(m_arr)

(3, 3)
[[0 1 2]
 [0 1 2]
 [0 1 2]]


In [23]:
w = np.linspace(1,10,50)
print( w )

[ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]


In [24]:
b = np.arange(1,30,3)
print(b)

[ 1  4  7 10 13 16 19 22 25 28]


In [27]:
b = np.linspace(1, 28, 10)
print(b)

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


In [34]:
b = np.linspace(1, 31, 10, False)
print(b)

[ 1.  4.  7. 10. 13. 16. 19. 22. 25. 28.]


In [44]:
x = np.arange(3)
y = np.arange(3,6)
z = np.arange(6,9)
m_arr = np.array([x,y,z], dtype= np.uint8)
print( m_arr.shape )
print(m_arr)
print(m_arr[1,2])
print(m_arr.dtype)

(3, 3)
[[0 1 2]
 [3 4 5]
 [6 7 8]]
5
uint8


### One-dimension Slicing

In [45]:
x = np.arange(1,10)
print(x)

[1 2 3 4 5 6 7 8 9]


In [47]:
print( x[2:7:2])

[3 5 7]


### Reshaping

In [77]:
x = np.arange(24).reshape(2, 3, -1)
print(x)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [78]:
y = x.reshape(-1)
print(y)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Multi-dimension Slicing

In [73]:
x = np.arange(24).reshape(2, 3, -1)
y = x[1,1:,:3] 
print(y)

[[16 17 18]
 [20 21 22]]


In [76]:
z = x[x>3]
print(z)

[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


### Manipulating Array Shapes

In [86]:
x = np.arange(24).reshape(2, 3, -1)
w = x.flatten()
w[2] = 100
print(w)
print(x.ravel())

[  0   1 100   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [89]:
y = np.arange(9)
y.shape = [3,3]
print(y)
print(y.T)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[0 3 6]
 [1 4 7]
 [2 5 8]]


In [88]:
print( np.resize(y,(6,6)))

[[0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]
 [0 1 2 3 4 5]
 [6 7 8 0 1 2]
 [3 4 5 6 7 8]]


In [93]:
print(np.ones((3,5), dtype=int))

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [94]:
print( np.eye(5) )

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [96]:
print( np.random.rand(6,4) )

[[0.58369238 0.56085463 0.98581105 0.32473226]
 [0.44765054 0.72777197 0.758409   0.22119676]
 [0.76565339 0.78884018 0.8844923  0.02744545]
 [0.36417554 0.60050451 0.1512212  0.70913366]
 [0.66702941 0.25240991 0.6089537  0.96201526]
 [0.8939778  0.8563365  0.63798984 0.77686602]]


### Matrix Multipication

In [98]:
mat_a = np.matrix([0,3,5,6,6,2]).reshape(2,3)
mat_a

matrix([[0, 3, 5],
        [6, 6, 2]])

In [99]:
mat_b = np.matrix([4,3,4,-2,6,-2]).reshape(3,2)
mat_b

matrix([[ 4,  3],
        [ 4, -2],
        [ 6, -2]])

In [101]:
mat_c = np.matmul(mat_a, mat_b)
mat_c 

matrix([[ 42, -16],
        [ 60,   2]])

In [102]:
mat_a @ mat_b

matrix([[ 42, -16],
        [ 60,   2]])

### Stacking

In [103]:
x = np.arange(4).reshape(2,2)
y = np.arange(4,8).reshape(2,2)
print(x)
print(y)

[[0 1]
 [2 3]]
[[4 5]
 [6 7]]


In [105]:
z = np.hstack((x,y))
print(z)
print(z.shape)

[[0 1 4 5]
 [2 3 6 7]]
(2, 4)


In [106]:
w = np.vstack((x,y))
print(w)
print(w.shape)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
(4, 2)


In [109]:
v= np.concatenate((x,y),axis=1)
print(v)
print( v = z)

[[0 1 4 5]
 [2 3 6 7]]
[[ True  True  True  True]
 [ True  True  True  True]]


In [110]:
d = np.dstack((x,y))
print(d)

[[[0 4]
  [1 5]]

 [[2 6]
  [3 7]]]


In [111]:
c = np.column_stack((x,y))
print(c)

[[0 1 4 5]
 [2 3 6 7]]


In [112]:
r = np.row_stack((x,y))
print(r)

[[0 1]
 [2 3]
 [4 5]
 [6 7]]
